// Typelizer digest e9c727857bddb2c9c486a68bf7a0de4b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User, Session} from '@/types'

type Auth = {
  user: User;
  session: Session;
}

export default Auth;
