// Typelizer digest 5c8311bdf86f5b7572b202327953ecec
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User, Session} from '@/types'

type Auth = {
  user: User;
  session: Session;
}

export default Auth;
