// Typelizer digest 6a1840911deef0a61af477dd94f6f568
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type IdentityPasswordResetsEdit = {
  email: string;
  sid?: string;
}

export default IdentityPasswordResetsEdit;
