// Typelizer digest 6f21d3acb33627d9a230cfa1bc140e05
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type IdentityPasswordResetsEdit = {
  email: string;
  sid?: string;
}

export default IdentityPasswordResetsEdit;
