// Typelizer digest ee9e08c2ab4383b188b687187c616d9b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Session = {
  id: number;
}

type SessionDetailsTrait = {
  user_agent: string | null;
  ip_address: string | null;
  created_at: string;
}

export default Session;
export type { SessionDetailsTrait };
