// Typelizer digest 29f1d80675cd43bb64942096d4c48d23
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Session = {
  id: number;
}

type SessionDetailsTrait = {
  user_agent: string | null;
  ip_address: string | null;
  created_at: string;
}

export default Session;
export type { SessionDetailsTrait };
