// Typelizer digest e69b8866f610ba0849dda7a44f4b4972
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Session, SessionDetailsTrait} from '@/types'

type SettingsSessionsIndex = {
  sessions: Array<Session & SessionDetailsTrait>;
}

export default SettingsSessionsIndex;
