// Typelizer digest 828615176a64fb2ba75b2d47f4863a87
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Session, SessionDetailsTrait} from '@/types'

type SettingsSessionsIndex = {
  sessions: Array<Session & SessionDetailsTrait>;
}

export default SettingsSessionsIndex;
