// Typelizer digest ba9adc79ebdf92025a251741c018f775
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Auth} from '@/types'

type SharedProps = {
  auth: Auth;
}

export default SharedProps;
