// Typelizer digest 34154ab0393e6eee4c5fa51cd5345f24
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Auth} from '@/types'

type SharedProps = {
  auth: Auth;
}

export default SharedProps;
