// Typelizer digest b8d3c3eac4b89ac9ff8e75120fcdf14a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  verified: boolean;
  created_at: string;
  updated_at: string;
}

export default User;
