// Typelizer digest 6dc76f4ac4e0569b14fd395215e42125
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  verified: boolean;
  created_at: string;
  updated_at: string;
}

export default User;
